/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BulletinRouteImport } from './routes/bulletin'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as LiveRouteImport } from './routes/live'
import { Route as RevealsRouteImport } from './routes/reveals'
import { Route as TrailerRouteImport } from './routes/trailer'
import { Route as RosterIndexRouteImport } from './routes/roster.index'
import { Route as RosterFileIdRouteImport } from './routes/roster.$fileId'
import { Route as ApiPublicGuestPhotoSplatRouteImport } from './routes/api/public/guest-photo.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinRoute = BulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealsRoute = RevealsRouteImport.update({
  id: '/reveals',
  path: '/reveals',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerRoute = TrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterFileIdRoute = RosterFileIdRouteImport.update({
  id: '/roster/$fileId',
  path: '/roster/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuestPhotoSplatRoute =
  ApiPublicGuestPhotoSplatRouteImport.update({
    id: '/api/public/guest-photo/$',
    path: '/api/public/guest-photo/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bulletin': typeof BulletinRoute
  '/connect': typeof ConnectRoute
  '/live': typeof LiveRoute
  '/reveals': typeof RevealsRoute
  '/trailer': typeof TrailerRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster/': typeof RosterIndexRoute
  '/api/public/guest-photo/$': typeof ApiPublicGuestPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bulletin': typeof BulletinRoute
  '/connect': typeof ConnectRoute
  '/live': typeof LiveRoute
  '/reveals': typeof RevealsRoute
  '/trailer': typeof TrailerRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster': typeof RosterIndexRoute
  '/api/public/guest-photo/$': typeof ApiPublicGuestPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bulletin': typeof BulletinRoute
  '/connect': typeof ConnectRoute
  '/live': typeof LiveRoute
  '/reveals': typeof RevealsRoute
  '/trailer': typeof TrailerRoute
  '/roster/$fileId': typeof RosterFileIdRoute
  '/roster/': typeof RosterIndexRoute
  '/api/public/guest-photo/$': typeof ApiPublicGuestPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bulletin'
    | '/connect'
    | '/live'
    | '/reveals'
    | '/trailer'
    | '/roster/$fileId'
    | '/roster/'
    | '/api/public/guest-photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bulletin'
    | '/connect'
    | '/live'
    | '/reveals'
    | '/trailer'
    | '/roster/$fileId'
    | '/roster'
    | '/api/public/guest-photo/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bulletin'
    | '/connect'
    | '/live'
    | '/reveals'
    | '/trailer'
    | '/roster/$fileId'
    | '/roster/'
    | '/api/public/guest-photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BulletinRoute: typeof BulletinRoute
  ConnectRoute: typeof ConnectRoute
  LiveRoute: typeof LiveRoute
  RevealsRoute: typeof RevealsRoute
  TrailerRoute: typeof TrailerRoute
  RosterFileIdRoute: typeof RosterFileIdRoute
  RosterIndexRoute: typeof RosterIndexRoute
  ApiPublicGuestPhotoSplatRoute: typeof ApiPublicGuestPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin': {
      id: '/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof BulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveals': {
      id: '/reveals'
      path: '/reveals'
      fullPath: '/reveals'
      preLoaderRoute: typeof RevealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer': {
      id: '/trailer'
      path: '/trailer'
      fullPath: '/trailer'
      preLoaderRoute: typeof TrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$fileId': {
      id: '/roster/$fileId'
      path: '/roster/$fileId'
      fullPath: '/roster/$fileId'
      preLoaderRoute: typeof RosterFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guest-photo/$': {
      id: '/api/public/guest-photo/$'
      path: '/api/public/guest-photo/$'
      fullPath: '/api/public/guest-photo/$'
      preLoaderRoute: typeof ApiPublicGuestPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BulletinRoute: BulletinRoute,
  ConnectRoute: ConnectRoute,
  LiveRoute: LiveRoute,
  RevealsRoute: RevealsRoute,
  TrailerRoute: TrailerRoute,
  RosterFileIdRoute: RosterFileIdRoute,
  RosterIndexRoute: RosterIndexRoute,
  ApiPublicGuestPhotoSplatRoute: ApiPublicGuestPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
